version: 2
jobs:
  publish:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish
  test:
    docker:
      - image: rishabhpoddar/node-postgres-git
    steps:
      - run: service postgresql start
      - run: sleep 5
      - run: psql -c "CREATE DATABASE auth_session"
      - run: psql -c "ALTER USER postgres PASSWORD 'password'"
      - checkout
      - run: npm install -d
      - run: npm test

workflows:
  version: 2
  tagged-build:
    jobs:
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - test:
          filters:
            branches:
              only:
                - dev
                - master